const config={volunteer:['Volunteer','Tell us what you would like to do, when you are available, and what part of the district you know best.'],yard_sign:['Request a yard sign','Give us the delivery address and number of signs you need.'],house_party:['Host a house party','Tell us about your neighborhood, possible dates, and how many guests you could invite.'],host_event:['Host an event','Share the venue, audience, possible dates, and what you have in mind.'],rsvp:['Event RSVP','Reserve your place and tell us how many people will attend.'],general:['Contact the campaign','Tell us how you would like to help or what you need from the campaign.']};
const form=document.getElementById('involvement-form');const result=document.getElementById('result');
function select(type){if(!config[type])type='volunteer';document.getElementById('request-type').value=type;document.getElementById('form-title').textContent=config[type][0];document.getElementById('form-help').textContent=config[type][1];document.getElementById('quantity-field').hidden=type!=='yard_sign';document.getElementById('notes').placeholder=type==='volunteer'?'Canvassing, calls, texting, event crew, photos, organizing, election day…':'Anything the campaign should know';document.querySelectorAll('[data-type]').forEach(b=>b.classList.toggle('active',b.dataset.type===type))}
document.querySelectorAll('[data-type]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.type)));
form.addEventListener('submit',async e=>{e.preventDefault();result.textContent='Sending…';result.className='';const f=new FormData(form);const body=Object.fromEntries(f);body.consent=f.has('consent');body.source='get-involved';body.details={notes:body.notes,quantity:body.quantity};delete body.notes;delete body.quantity;try{const response=await fetch('/api/public/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not send your request.');result.textContent='Got it. The campaign has your request and will follow up.';result.className='success';form.reset()}catch(error){result.textContent=error.message;result.className='error'}});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setRsvp(eventId,title){select('rsvp');document.getElementById('form-title').textContent=title?`RSVP: ${title}`:'Event RSVP';let input=document.getElementById('event-id');if(!input){input=document.createElement('input');input.type='hidden';input.id='event-id';input.name='eventId';form.append(input)}input.value=eventId;form.scrollIntoView({behavior:'smooth'})}
fetch('/api/public/events').then(r=>r.json()).then(({events})=>{document.getElementById('events-list').innerHTML=events.length?events.map(e=>`<article class="event"><div><strong>${esc(e.title)}</strong><small>${new Intl.DateTimeFormat('en-US',{dateStyle:'full',timeStyle:'short',timeZone:e.timezone}).format(new Date(e.starts_at))} · ${esc([e.venue,e.city].filter(Boolean).join(', '))}</small></div><button data-rsvp="${e.id}" data-title="${esc(e.title)}">RSVP</button></article>`).join(''):'<p>No public events are scheduled yet. Check back soon.</p>';document.querySelectorAll('[data-rsvp]').forEach(b=>b.addEventListener('click',()=>setRsvp(b.dataset.rsvp,b.dataset.title)))}).catch(()=>document.getElementById('events-list').textContent='Events are temporarily unavailable.');
const params=new URLSearchParams(location.search);if(params.get('type')==='rsvp'&&params.get('eventId'))setRsvp(params.get('eventId'),params.get('title'));else select(params.get('type'));
const analyticsScript=document.createElement('script');analyticsScript.src='/analytics.js';analyticsScript.defer=true;document.head.append(analyticsScript);
