const slugify = (value) => value.toLowerCase().replace(/^the /, '').replace(/\$/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const P = (n,title,hook,promise,tag,body)=>({n,title,hook,promise,tag,body,slug:slugify(title),label:'PLAN '+n});
export const PLANS = [
P(1,'THE $500-A-MONTH FREEDOM PLAN','Put $500 a month back into the family budget.','$500 more freedom every month.','Money & Taxes','Make life at least $500 a month more affordable for Louisiana families. Not with another government check — by attacking the costs government helps create: taxes, energy bills, insurance costs, healthcare costs, housing costs, fees, and the hidden cost of regulation. Every major economic proposal gets measured by one question: does this leave Louisiana families with more money at the end of the month?'),
P(2,'THE $100,000 SMALL BUSINESS PLAN','Let small businesses grow before Washington treats them like big corporations.','Build the business first. Feed the bureaucracy later.','Business','The smallest businesses face paperwork, taxes, compliance costs and regulations designed for companies hundreds of times their size. Businesses with their first $100,000 in annual revenue should face dramatically simplified federal taxes, reporting and compliance requirements. The goal is to let people prove an idea, build a customer base and create jobs before Washington buries them in paperwork.'),
P(3,'THE $0 TAX ON TIPS PLAN',"If a customer leaves it for you, Washington shouldn't take it.",'You earned the tip. You keep the tip.','Work & Pay','Tips are earned by servers, bartenders, hairstylists, drivers, hospitality workers and millions of other Americans who often depend on variable income. Lisa supports eliminating federal income taxes on qualifying tip income. A customer rewarding good service shouldn\u2019t create another opportunity for Washington to take a cut.'),
P(4,'THE $0 TAX ON OVERTIME PLAN',"Working extra hours shouldn't mean paying extra taxes.",'Extra work should mean extra money.','Work & Pay','Overtime means missing dinner, giving up weekends, working nights, and spending more time away from family. Washington shouldn\u2019t punish people for working harder. Lisa supports eliminating federal income taxes on qualifying overtime earnings.'),
P(5,'THE TAX WORK LESS PLAN','Stop punishing people for earning a living.','Tax work less. Let workers keep more.','Money & Taxes','The federal government taxes wages before workers ever see their full paycheck. Lisa wants to move the tax burden away from productive work and dramatically reduce federal taxes on wages, particularly for working and middle-class Americans. Make work more rewarding, not more taxable.'),
P(6,'THE BABY FREEDOM ACCOUNT','Every child should begin adulthood with savings and ownership instead of debt.','Start every child with ownership, not dependence.','Money & Taxes','Parents, grandparents, relatives, employers, charities, churches and community organizations could contribute to a child\u2019s privately owned Freedom Account, with favorable tax treatment on contributions and growth, and the money eventually available for education, a first home, starting a business, or retirement. No taxpayer-funded deposit. No new entitlement. No government ownership of the account.'),
P(7,'THE 10-MINUTE BUSINESS PLAN','Starting a business should take minutes, not months.','Have an idea at breakfast. Be in business by lunch.','Business',"If your business isn't hurting anyone, government shouldn't make you ask permission to earn a living. Lisa wants a simple digital process allowing ordinary entrepreneurs to complete basic federal business requirements in roughly ten minutes, and would push to eliminate unnecessary licenses, registrations, filings and redundant federal requirements."),
P(8,'THE ONE-PAGE TAX PLAN',"If ordinary Americans can't understand the tax code, the tax code is broken.",'One page. No tax maze.','Money & Taxes',"Families shouldn't need accountants, lawyers, software subscriptions and hours of their lives just to tell Washington what they owe. Lisa wants a dramatically simpler tax system with a return most ordinary households can complete on one page. Fewer loopholes. Fewer special deals. Less paperwork."),
P(9,'THE KEEP YOUR HOUSE PLAN',"Paying off your mortgage shouldn't mean renting your home from government forever.","If you paid for your house, government shouldn't take it away.",'Home & Insurance','A person can spend decades paying for a home and still lose it because of taxes. Lisa wants stronger protections against people losing their primary residence solely because they cannot keep up with rising property-tax burdens, particularly seniors and longtime homeowners.'),
P(10,'THE FIRST HOME FREEDOM PLAN','Make it easier for working people to buy their first home.','Make the starter home possible again.','Home & Insurance',"Young families don't need another complicated housing bureaucracy. They need homes that cost less to build and more money left in their paycheck. Lisa wants to reduce federal rules that unnecessarily increase construction costs, encourage starter homes and innovative housing, and eliminate barriers that make smaller and more affordable homes difficult to build."),
P(11,'THE AFFORDABLE HOME PLAN','The solution to expensive housing is more housing.','Build more homes. Lower the price.','Home & Insurance','Government keeps subsidizing demand while restricting supply. Lisa wants to attack the cost of creating homes: faster permitting, fewer unnecessary federal building restrictions, easier modular and manufactured construction, stronger property rights, and more freedom for builders to create housing people can actually afford.'),
P(12,'THE INSURANCE FREEDOM PLAN','Louisiana families need competition, not another insurance bureaucracy.','More competition. Lower premiums.','Home & Insurance','Louisiana families are being hammered by insurance costs. Lisa wants to increase competition, remove unnecessary barriers to new insurers, expand consumer choice, increase pricing transparency, and fight regulations that make insurance more expensive without meaningfully protecting policyholders. No sweetheart deals. No protected monopolies. No taxpayer guarantees for politically connected companies.'),
P(13,'THE HEALTHCARE FREEDOM PLAN','Put patients and healthcare professionals back in charge.','Your healthcare should answer to you.','Health','Lisa spent her career as a nurse and worked on the frontlines in New Orleans during COVID. She saw what happens when politicians, bureaucracies, hospital systems and insurance companies insert themselves between patients and caregivers. Her plan expands direct care, price transparency, Health Savings Accounts, telemedicine, independent clinics and competition.'),
P(14,'THE CHEAP ENERGY PLAN','Louisiana should be one of the cheapest places in America to power a home or business.','Produce more. Pay less.','Energy','Louisiana sits on enormous energy advantages and Lisa wants to unleash them. Produce more energy. Build infrastructure faster. Reduce unnecessary permitting delays. Encourage oil, natural gas, nuclear and new technologies to compete. Stop Washington from artificially restricting supply.'),
P(15,'THE $2 GAS GOAL','Make dramatically cheaper gasoline a national economic goal.','More American energy. Cheaper American gas.','Energy','Every penny added to fuel eventually reaches groceries, construction, deliveries, restaurants and household budgets. Lisa wants Washington focused on increasing American energy supply enough to drive gasoline toward $2 a gallon whenever market conditions make it achievable. It is a goal, not a government price control.'),
P(16,'THE 30-DAY PERMIT PLAN',"Government shouldn't be allowed to leave people waiting forever.",'Government gets a deadline too.','Business','Businesses and builders can spend months or years waiting for federal approvals. Lisa wants a default rule: federal agencies get 30 days to approve, deny, or explain exactly what is missing. No indefinite bureaucratic limbo. For routine permits, failure to act should trigger automatic escalation or presumptive approval where legally appropriate.'),
P(17,'THE PAYCHECK PROTECTION PLAN',"Your paycheck shouldn't become Washington's emergency fund.",'Hands off the paycheck.','Money & Taxes',"Lisa wants to protect working families from sudden federal tax increases and hidden payroll grabs. Any proposal increasing taxes on ordinary workers should face a high legislative hurdle, full public disclosure, and a clear vote. She would oppose efforts to finance Washington's spending addiction by quietly taking more from every paycheck."),
P(18,'THE LOUISIANA MONEY STAYS IN LOUISIANA PLAN','Stop sending Louisiana dollars to Washington just to beg for some of them back.','Louisiana money should build Louisiana, not Washington.','Louisiana','The federal government collects money from Louisiana, runs it through a giant bureaucracy, attaches conditions, takes its cut, and sends portions back. Lisa wants to keep more decisions and resources closer to home. Whenever a federal program can responsibly be returned to states, communities, families or individuals, she will push to do it.'),
P(19,'THE NO TAX ON NECESSITIES PLAN',"Government shouldn't make basic survival more expensive.","Don't tax what families have to buy.",'Money & Taxes',"Food. Medicine. Diapers. Basic clothing. Household essentials. Lisa supports removing federal taxes, tariffs and unnecessary government charges that raise the cost of essential goods. Government shouldn't profit because people need to eat, care for children, or stay healthy."),
P(20,'THE PRESCRIPTION FREEDOM PLAN','Make medicine cheaper by expanding competition and patient choice.','More competition. Cheaper medicine.','Health','Americans frequently pay more for medicine than people purchasing identical products elsewhere. Lisa wants faster generic competition, greater price transparency, more freedom to purchase safe medicines across markets, and fewer government barriers that protect entrenched pharmaceutical interests.'),
P(21,'THE SECOND CHANCE PLAN',"A past mistake shouldn't become a lifetime sentence.",'Serve the sentence. Get your life back.','Rights & Privacy','People who have completed sentences for nonviolent offenses should have a genuine path back into productive life. Lisa wants to reduce federal barriers that prevent people with old convictions from getting jobs, licenses, housing, education, or starting businesses. Public safety matters. So does allowing people who have paid their debt to rebuild.'),
P(22,'THE END THE WAR ON WEED PLAN','Stop ruining lives over marijuana.','Stop arresting people over a plant.','Rights & Privacy','The federal marijuana war has consumed enormous resources, criminalized peaceful behavior, created black markets, and left people carrying records that can follow them for decades. Lisa supports ending federal marijuana prohibition, removing marijuana from federal prohibition schedules, and clearing appropriate federal marijuana convictions.'),
P(23,'THE WARRANT MEANS WARRANT PLAN',"Government shouldn't be able to buy its way around the Fourth Amendment.",'If government wants your data, get a warrant.','Rights & Privacy',"If government needs a warrant to demand your information directly, it shouldn't be able to purchase the same information from a private data broker without one. Location data. Search histories. Private communications. Financial information. Personal records. Lisa wants digital information to receive strong Fourth Amendment protection."),
P(24,'THE NO DIGITAL PAPERS PLAN','Americans should not need government permission to exist in everyday society.','No permission slip for everyday life.','Rights & Privacy','Lisa opposes mandatory federal digital identification systems that could become necessary to work, travel, bank, communicate, purchase goods, or participate in ordinary life. Digital credentials may be useful when voluntarily chosen. They become dangerous when government makes them compulsory.'),
P(25,'THE NO GOVERNMENT MONEY TRACKER PLAN','Your money should not become a government surveillance device.',"Your money shouldn't report on you.",'Rights & Privacy','Lisa opposes a retail Central Bank Digital Currency that allows the federal government to directly monitor, restrict, freeze, expire, or program how lawful money is used. She supports cash, financial privacy, decentralized alternatives, and the right to conduct lawful transactions without government creating a permanent record of everyday life.'),
P(26,'THE CAMERA WARRANT PLAN','Public safety cameras should not become a nationwide movement database.','Follow criminals, not citizens.','Rights & Privacy','License plate readers, facial recognition systems, drones and networked surveillance cameras can allow government to reconstruct where innocent Americans travel and whom they meet. Lisa wants strict warrant requirements and retention limits for government use of mass surveillance data. Investigate suspects. Don\u2019t track everybody.'),
P(27,'THE 72-HOUR TRANSPARENCY PLAN','No more voting on bills nobody had time to read.','Read it before you vote on it.','Accountability','Thousands of pages should not appear in the middle of the night and receive a vote hours later. Lisa wants final legislative text publicly available for at least 72 hours before a House vote, except for genuine, narrowly defined emergencies. The public deserves time to see what Congress is doing.'),
P(28,'THE ONE SUBJECT, ONE BILL PLAN','Stop hiding bad laws inside giant bills.','One bill. One subject. One vote.','Accountability',"A farm bill shouldn't contain unrelated surveillance policy. A defense bill shouldn't become a vehicle for dozens of unrelated programs. Lisa supports requiring legislation to address one clearly defined subject so members of Congress cannot bury controversial provisions inside massive must-pass packages."),
P(29,'THE POLITICIANS LIVE UNDER IT TOO PLAN','Congress should never exempt itself from the laws it passes.','No special rules for politicians.','Accountability','If a law is good enough for you, it should be good enough for the people who voted for it. Lisa wants members of Congress and senior federal officials subject to the same rules, mandates, restrictions and programs they impose on everyone else. No congressional carve-outs. No ruling class.'),
P(30,'THE KEEP YOUR OVERTIME PLAN','Every extra hour should belong to the worker who earned it.','Work the extra hour. Keep the extra dollar.','Work & Pay','The broader worker-focused companion to the $0 Tax on Overtime Plan. Lisa wants workers to keep more of every overtime dollar by eliminating federal income taxes on qualifying overtime and fighting policies that make employers less willing to offer overtime opportunities.'),
P(31,'THE KEEP YOUR TIPS PLAN','The person who earned the tip should keep the tip.','Your customer tipped you, not Congress.','Work & Pay','The worker-focused companion to the $0 Tax on Tips Plan. Lisa wants qualifying tips protected from federal income taxation and opposes efforts to treat gratuities as another easy source of revenue for Washington.'),
P(32,'THE REBUILD LOUISIANA PLAN','Louisiana sends too much money away and waits too long to get too little back.','Louisiana builds. Washington gets out of the way.','Louisiana','Roads. Bridges. Ports. Drainage. Water systems. Power infrastructure. Louisiana has enormous infrastructure needs, while federal bureaucracy routinely makes projects slower and more expensive. Lisa wants to send greater authority and resources closer to Louisiana, streamline federal permitting, eliminate expensive strings attached to infrastructure funding, and prioritize the infrastructure that allows people and businesses to prosper.')
];


export const ISSUE_PAGES = [
  {slug:'cost-of-living', title:'Cost of Living in Louisiana', description:'Lisa Ballay’s plan to lower the cost of living for families in New Orleans and Louisiana’s 2nd Congressional District.', tags:['Money & Taxes','Work & Pay','Energy'], intro:'Louisiana families feel Washington’s decisions in every grocery bill, utility payment, gallon of gas, and paycheck. Lisa’s affordability agenda measures policy by a practical standard: does it leave families with more money and more control over their lives?'},
  {slug:'homeowners-insurance', title:'Louisiana Homeowners Insurance', description:'Lisa Ballay’s approach to Louisiana’s homeowners insurance crisis: competition, transparency, choice, and lower costs.', tags:['Home & Insurance'], intro:'Homeowners across Louisiana are being squeezed by premiums, limited choices, and uncertainty. Lisa wants more competition and pricing transparency without creating another bureaucracy or guaranteeing profits for politically connected companies.'},
  {slug:'healthcare', title:'Affordable Healthcare for Louisiana', description:'A New Orleans nurse’s plan for more affordable healthcare, transparent prices, patient choice, and independent care.', tags:['Health'], intro:'Lisa worked as a nurse and saw what happens when distant rules collide with patients, caregivers, and household budgets. Her healthcare agenda puts patients and healthcare professionals back in charge.'},
  {slug:'housing', title:'Housing and Homeownership in Louisiana', description:'Lisa Ballay’s plans to make housing and first-time homeownership more affordable in Louisiana District 2.', tags:['Home & Insurance'], intro:'Working families need more homes they can afford, not more complicated programs that increase demand while supply stays restricted. Lisa supports faster permitting, starter homes, property rights, and lower construction barriers.'},
  {slug:'small-business', title:'Small Business Freedom in Louisiana', description:'Lisa Ballay’s plan to make it faster and less expensive to start and grow a small business in New Orleans and Louisiana.', tags:['Business'], intro:'Entrepreneurs should be able to test an idea and serve customers before paperwork consumes their time and money. Lisa wants simpler rules, firm agency deadlines, and fewer barriers to earning a living.'},
  {slug:'taxes-and-paychecks', title:'Taxes, Tips, Overtime, and Paychecks', description:'Lisa Ballay’s plans to help Louisiana workers keep more tips, overtime earnings, and take-home pay.', tags:['Work & Pay','Money & Taxes'], intro:'Extra work should produce extra take-home pay. Lisa supports protecting tips and qualifying overtime from federal income taxes while simplifying the tax system for ordinary families.'},
  {slug:'privacy-and-surveillance', title:'Privacy and the Fourth Amendment', description:'Lisa Ballay’s Libertarian plans to protect Louisiana residents from warrantless digital and financial surveillance.', tags:['Rights & Privacy'], intro:'Constitutional rights do not disappear when personal information becomes digital. Lisa supports warrant requirements, limits on mass surveillance, financial privacy, and voluntary—not compulsory—digital tools.'},
  {slug:'government-accountability', title:'Government Transparency and Accountability', description:'Lisa Ballay’s plans for readable bills, public review, single-subject legislation, and equal rules for Congress.', tags:['Accountability','Louisiana'], intro:'Congress should read bills before voting, give the public time to review them, and live under the same laws it imposes. Lisa’s accountability plans make government simpler to inspect and harder to game.'}
];
