import { ISSUE_PAGES, PLANS } from './seo-content.js';

export const SITE_URL = 'https://ballayforcongress.com';

const escapeHtml = (value = '') => String(value).replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const pageUrl = (path) => `${SITE_URL}${path}`;
const planPath = (plan) => `/freedom-plans/${plan.slug}`;

const styles = `
:root{--purple:#3a0660;--deep:#1e0733;--gold:#fbb701;--green:#02961b;--paper:#faf6ef;--muted:#665d6c}*{box-sizing:border-box}body{margin:0;color:var(--deep);background:var(--paper);font-family:Arial,Helvetica,sans-serif;line-height:1.65}a{color:#68179d}a:hover{color:#8b24c8}header{background:#210339;color:#fff;border-bottom:5px solid var(--gold)}.nav{max-width:1160px;margin:auto;padding:16px 22px;display:flex;align-items:center;gap:22px;flex-wrap:wrap}.brand{font-weight:900;letter-spacing:.08em;color:#fff;text-decoration:none}.nav nav{display:flex;gap:18px;flex-wrap:wrap;margin-left:auto}.nav nav a{color:#fff;text-decoration:none;font-weight:700}.cta{background:var(--gold);color:var(--deep)!important;padding:9px 15px;border-radius:6px}.hero{background:linear-gradient(145deg,var(--purple),#180029);color:#fff;padding:66px 22px}.wrap{max-width:1060px;margin:auto}.eyebrow{text-transform:uppercase;letter-spacing:.16em;font-weight:800;color:var(--gold);font-size:.78rem}.hero h1{font-size:clamp(2.25rem,7vw,5.4rem);line-height:.96;max-width:900px;margin:.2em 0}.hero p{font-size:1.18rem;max-width:720px}.content{padding:54px 22px}.content h2{font-size:clamp(1.7rem,4vw,2.7rem);line-height:1.1}.lede{font-size:1.2rem;max-width:760px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:18px;margin:28px 0}.card{background:#fff;border:1px solid #ddd3e2;border-radius:14px;padding:23px;box-shadow:0 10px 30px rgba(30,7,51,.05)}.card h2,.card h3{margin-top:0;line-height:1.15}.card a{font-weight:800}.tag{display:inline-block;background:#eee4f4;color:var(--purple);padding:4px 9px;border-radius:20px;font-size:.76rem;font-weight:800}.promise{border-left:5px solid var(--gold);padding:15px 20px;background:#fff7da;font-weight:800;font-size:1.1rem}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:26px}.button{display:inline-block;text-decoration:none;font-weight:900;padding:13px 19px;border-radius:7px;background:var(--deep);color:#fff}.button.gold{background:var(--gold);color:var(--deep)}.breadcrumbs{font-size:.88rem;color:var(--muted);margin-bottom:28px}.faq details{background:#fff;border:1px solid #ddd3e2;border-radius:10px;padding:14px 18px;margin:10px 0}.faq summary{font-weight:800;cursor:pointer}footer{background:#16002b;color:#ddd;padding:35px 22px;margin-top:50px}footer a{color:var(--gold)}@media(max-width:700px){.nav nav{margin-left:0}.hero{padding-top:45px}.hero h1{font-size:2.55rem}}
`;

function jsonLd(data) {
  return `<script type="application/ld+json">${JSON.stringify(data).replace(/</g, '\\u003c')}</script>`;
}

function layout({ title, description, path, eyebrow, heading, intro, body, schema = [] }) {
  const canonical = pageUrl(path);
  const graph = [
    { '@type':'WebSite', '@id':`${SITE_URL}/#website`, url:`${SITE_URL}/`, name:'Lisa Ballay for Congress' },
    ...schema,
  ];
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(description)}"><link rel="canonical" href="${canonical}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><meta property="og:type" content="article"><meta property="og:site_name" content="Lisa Ballay for Congress"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${SITE_URL}/assets/yard-sign.png"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#3a0660">${jsonLd({'@context':'https://schema.org','@graph':graph})}<style>${styles}</style></head><body><header><div class="nav"><a class="brand" href="/">LISA BALLAY</a><nav aria-label="Main navigation"><a href="/lisa-ballay">Meet Lisa</a><a href="/louisiana-district-2">District 2</a><a href="/issues">Issues</a><a href="/freedom-plans">Freedom Plans</a><a class="cta" href="/get-involved">Get involved</a></nav></div></header><main><section class="hero"><div class="wrap"><div class="eyebrow">${escapeHtml(eyebrow)}</div><h1>${escapeHtml(heading)}</h1><p>${escapeHtml(intro)}</p></div></section><div class="content"><div class="wrap"><div class="breadcrumbs"><a href="/">Home</a> / ${escapeHtml(heading)}</div>${body}</div></div></main><footer><div class="wrap"><strong>Lisa Ballay for Congress</strong><br>Libertarian candidate · Louisiana's 2nd Congressional District · New Orleans, Louisiana<br><a href="mailto:hello@ballayforcongress.com">hello@ballayforcongress.com</a><p>Paid for by Lisa Ballay for Congress.</p></div></footer></body></html>`;
}

const card = (href, title, text, tag = '') => `<article class="card">${tag ? `<span class="tag">${escapeHtml(tag)}</span>` : ''}<h2><a href="${href}">${escapeHtml(title)}</a></h2><p>${escapeHtml(text)}</p></article>`;

export function renderPlansIndex() {
  const cards = PLANS.map((plan) => card(planPath(plan), plan.title.replace(/^THE /, ''), plan.hook, plan.tag)).join('');
  return layout({title:'Lisa Ballay’s 32 Freedom Plans | Louisiana District 2',description:'Explore Lisa Ballay’s 32 Libertarian Freedom Plans for affordability, housing, insurance, healthcare, small business, privacy, and accountable government.',path:'/freedom-plans',eyebrow:'Make Louisiana Affordable Again',heading:'32 Freedom Plans',intro:'Big problems deserve clear plans. Explore Lisa Ballay’s proposals to help Louisiana families keep more money and more control over their lives.',body:`<p class="lede">Every plan answers a practical question: will this make it easier to live, work, build, and raise a family in Louisiana?</p><div class="grid">${cards}</div><div class="actions"><a class="button gold" href="/get-involved">Help put these plans to work</a><a class="button" href="/issues">Browse by issue</a></div>`,schema:[{'@type':'CollectionPage','@id':`${SITE_URL}/freedom-plans#page`,url:`${SITE_URL}/freedom-plans`,name:'Lisa Ballay’s 32 Freedom Plans',mainEntity:{'@type':'ItemList',numberOfItems:PLANS.length,itemListElement:PLANS.map((p,i)=>({'@type':'ListItem',position:i+1,url:pageUrl(planPath(p)),name:p.title}))}}]});
}

export function renderPlan(plan) {
  const related = PLANS.filter((candidate) => candidate.tag === plan.tag && candidate.n !== plan.n).slice(0,3);
  return layout({title:`${plan.title.replace(/^THE /,'')} | Lisa Ballay for Congress`,description:`${plan.hook} Read Lisa Ballay’s ${plan.tag.toLowerCase()} proposal for Louisiana’s 2nd Congressional District.`,path:planPath(plan),eyebrow:`Freedom Plan ${plan.n} of 32 · ${plan.tag}`,heading:plan.title.replace(/^THE /,''),intro:plan.hook,body:`<p class="promise">${escapeHtml(plan.promise)}</p><h2>The plan</h2><p class="lede">${escapeHtml(plan.body)}</p><h2>Why it matters in Louisiana</h2><p>Families and small businesses in New Orleans and across Louisiana’s 2nd Congressional District feel federal taxes, rules, delays, and hidden costs in everyday bills. Lisa will judge proposals by whether they expand choice, reduce unnecessary costs, protect individual rights, and leave decisions closer to the people affected.</p><div class="actions"><a class="button gold" href="/get-involved">Join the campaign</a><a class="button" href="/freedom-plans">See all 32 plans</a></div><h2>Related Freedom Plans</h2><div class="grid">${related.map((p)=>card(planPath(p),p.title.replace(/^THE /,''),p.hook,p.tag)).join('')}</div>`,schema:[{'@type':'Article','@id':`${pageUrl(planPath(plan))}#article`,headline:plan.title,description:plan.hook,author:{'@type':'Person',name:'Lisa Ballay'},publisher:{'@type':'Organization',name:'Lisa Ballay for Congress'},mainEntityOfPage:pageUrl(planPath(plan)),about:['Louisiana’s 2nd Congressional District',plan.tag]}]});
}

export function renderIssuesIndex() {
  return layout({title:'Issues | Lisa Ballay for Louisiana District 2',description:'Lisa Ballay’s Libertarian positions on affordability, insurance, healthcare, housing, small business, paychecks, privacy, and accountable government.',path:'/issues',eyebrow:'Issues',heading:'Make it cheaper to live. Easier to work. Easier to build.',intro:'Lisa Ballay’s campaign starts with affordability, freedom, and practical results for New Orleans and Louisiana’s 2nd Congressional District.',body:`<div class="grid">${ISSUE_PAGES.map((issue)=>card(`/issues/${issue.slug}`,issue.title,issue.description)).join('')}</div><div class="actions"><a class="button gold" href="/freedom-plans">Explore all 32 Freedom Plans</a></div>`,schema:[{'@type':'CollectionPage',name:'Lisa Ballay on the Issues',url:`${SITE_URL}/issues`}]});
}

export function renderIssue(issue) {
  const plans = PLANS.filter((plan) => issue.tags.includes(plan.tag));
  const faq = [
    {q:`What is Lisa Ballay’s approach to ${issue.title.toLowerCase()}?`,a:'Lisa starts with affordability, individual choice, transparent costs, and moving decisions closer to the people affected rather than expanding distant bureaucracy.'},
    {q:'Who does Lisa Ballay represent?',a:'Lisa Ballay is a Libertarian candidate for the U.S. House in Louisiana’s 2nd Congressional District, with a campaign based in the New Orleans area.'},
    {q:'How can District 2 residents help?',a:'Residents can volunteer, request a yard sign, host an event, introduce Lisa to community members, or support the campaign through the Get Involved page.'},
  ];
  return layout({title:`${issue.title} | Lisa Ballay for Congress`,description:issue.description,path:`/issues/${issue.slug}`,eyebrow:'Louisiana District 2 Issues',heading:issue.title,intro:issue.intro,body:`<h2>Lisa’s approach</h2><p class="lede">${escapeHtml(issue.intro)}</p><p>Lisa is a nurse, mother, and grandmother—not a career politician. She measures government proposals by their real effect on household bills, opportunity, freedom, and the ability of Louisiana communities to solve problems close to home.</p><h2>Related Freedom Plans</h2><div class="grid">${plans.map((p)=>card(planPath(p),p.title.replace(/^THE /,''),p.hook,p.tag)).join('')}</div><section class="faq"><h2>Frequently asked questions</h2>${faq.map((x)=>`<details><summary>${escapeHtml(x.q)}</summary><p>${escapeHtml(x.a)}</p></details>`).join('')}</section><div class="actions"><a class="button gold" href="/get-involved">Get involved in District 2</a><a class="button" href="/issues">All issues</a></div>`,schema:[{'@type':'Article',headline:issue.title,author:{'@type':'Person',name:'Lisa Ballay'},publisher:{'@type':'Organization',name:'Lisa Ballay for Congress'},mainEntityOfPage:pageUrl(`/issues/${issue.slug}`)},{'@type':'FAQPage',mainEntity:faq.map((x)=>({'@type':'Question',name:x.q,acceptedAnswer:{'@type':'Answer',text:x.a}}))}]});
}

export function renderLisa() {
  return layout({title:'Meet Lisa Ballay | Louisiana District 2 Libertarian',description:'Meet Lisa Ballay, a New Orleans nurse, wife, mother, grandmother, and Libertarian candidate for Congress in Louisiana’s 2nd District.',path:'/lisa-ballay',eyebrow:'Meet Lisa Ballay',heading:'A nurse, Louisiana mom, and grandmother—not a career politician.',intro:'Lisa Ballay is running for Congress because families deserve lower costs, more choices, and a government that stays out of their wallets and their way.',body:`<div class="grid"><article class="card"><h2>The frontline</h2><p>During COVID, Lisa worked on the frontlines in New Orleans. She experienced what happens when decisions made far away collide with patients, families, nurses, workers, and businesses.</p></article><article class="card"><h2>The nurse’s view</h2><p>A career in healthcare taught Lisa that coverage is not the same as affordability. A program’s name matters less than whether a family can pay the bill.</p></article><article class="card"><h2>The reason</h2><p>Lisa is a wife, mother, and grandmother who believes the people closest to a problem usually understand it better than distant officials.</p></article></div><h2>What Lisa is fighting for</h2><p class="lede">More money left on Friday. A lower bill next month. A business you can start. A house and healthcare you can afford. A future you can build.</p><div class="actions"><a class="button gold" href="/get-involved">Meet and support Lisa</a><a class="button" href="/freedom-plans">Read Lisa’s plans</a></div>`,schema:[{'@type':'Person','@id':`${SITE_URL}/#lisa-ballay`,name:'Lisa Ballay',url:`${SITE_URL}/lisa-ballay`,image:`${SITE_URL}/assets/lisa-headshot.jpg`,jobTitle:'Candidate for U.S. House of Representatives',memberOf:{'@type':'Organization',name:'Libertarian Party'},homeLocation:{'@type':'Place',name:'New Orleans, Louisiana'}}]});
}

export function renderDistrict() {
  return layout({title:'Louisiana’s 2nd Congressional District | Lisa Ballay',description:'Learn about Lisa Ballay’s 2026 campaign for Louisiana’s 2nd Congressional District, centered on New Orleans, affordability, freedom, and accountable government.',path:'/louisiana-district-2',eyebrow:'2026 Congressional Election',heading:'Louisiana’s 2nd Congressional District',intro:'Lisa Ballay is running to represent District 2 with a Libertarian agenda built around affordability, individual rights, and local control.',body:`<h2>A campaign rooted in the New Orleans area</h2><p class="lede">District 2 voters deserve a representative who asks what federal policy actually costs families, workers, homeowners, patients, and neighborhood businesses.</p><div class="grid"><article class="card"><h2>Affordability</h2><p>Lower the costs government helps create and let families keep more of what they earn.</p></article><article class="card"><h2>Freedom</h2><p>Protect privacy, property, choice, and the right to build a life without unnecessary permission.</p></article><article class="card"><h2>Accountability</h2><p>Readable bills, public review, clear votes, and no special rules for politicians.</p></article></div><p><strong>Election information changes.</strong> Voters should confirm registration, polling locations, sample ballots, and current deadlines through the Louisiana Secretary of State.</p><div class="actions"><a class="button gold" href="/get-involved">Volunteer in District 2</a><a class="button" href="/issues">Explore the issues</a></div>`,schema:[{'@type':'WebPage',name:'Louisiana’s 2nd Congressional District',about:{'@type':'AdministrativeArea',name:'Louisiana’s 2nd Congressional District'}}]});
}

export function renderActionPage(kind) {
  const pages = {
    volunteer:{path:'/volunteer',title:'Volunteer for Lisa Ballay in Louisiana District 2',heading:'Volunteer for Lisa Ballay',intro:'Help reach voters across New Orleans and Louisiana’s 2nd Congressional District.',copy:'Knock doors, make calls, help at events, introduce Lisa to neighbors, or lend your professional skills. Every volunteer helps build a campaign powered by people rather than a party machine.'},
    'yard-signs':{path:'/yard-signs',title:'Lisa Ballay Yard Signs | Louisiana District 2',heading:'Request a Lisa Ballay yard sign',intro:'Show your support in New Orleans and across Louisiana’s 2nd Congressional District.',copy:'Request a campaign yard sign for your home or business. The campaign will follow up about availability and delivery or pickup.'},
    'friends-of-lisa':{path:'/friends-of-lisa',title:'Friends of Lisa | Support Lisa Ballay for Congress',heading:'Friends of Lisa',intro:'Turn personal relationships into a people-powered campaign.',copy:'Introduce Lisa to neighbors, volunteers, donors, community leaders, organizations, event hosts, and local media. The most useful question in this campaign is simple: who should Lisa meet next?'}
  };
  const page = pages[kind];
  const type = kind === 'yard-signs' ? 'yard_sign' : kind === 'friends-of-lisa' ? 'general' : 'volunteer';
  return layout({title:page.title,description:`${page.intro} ${page.copy}`,path:page.path,eyebrow:'People-Powered Campaign',heading:page.heading,intro:page.intro,body:`<p class="lede">${escapeHtml(page.copy)}</p><div class="actions"><a class="button gold" href="/get-involved?type=${type}">Start here</a><a class="button" href="/lisa-ballay">Meet Lisa</a></div>`,schema:[{'@type':'WebPage',name:page.heading,url:pageUrl(page.path)}]});
}

export const SEO_PATHS = [
  '/lisa-ballay','/louisiana-district-2','/issues',...ISSUE_PAGES.map((x)=>`/issues/${x.slug}`),'/freedom-plans',...PLANS.map(planPath),'/volunteer','/yard-signs','/friends-of-lisa','/get-involved'
];

export { ISSUE_PAGES, PLANS };
